<!DOCTYPE html>
<html>

<body>
    <h1>Simulation of a spirograph</h1>
    <input type="text" id="nout" value='96' onchange="fire()"> number of teeth on the frame<br>
    <input type="text" id="nin" value='33' onchange="fire()"> number of teeth on the gear<br>
    <input type="text" id="p" value='0.5' onchange="fire()"> position of hole. 0: on the center. 1: on the edge<br>

    <canvas id="myCanvas" width="800" height="800" style="border:1px solid #d3d3d3;">
    Your browser does not support the HTML5 canvas tag.</canvas>
    
    <script>
        // functions
        function gcd_two_numbers(x, y) {
            x = Math.abs(x);
            y = Math.abs(y);
            while (y) {
                var t = y;
                y = x % y;
                x = t;
            }
            return x;
        }

        function lcm(x, y) {
            if ((typeof x !== 'number') || (typeof y !== 'number'))
                return false;
            return (!x || !y) ? 0 : Math.abs((x * y) / gcd_two_numbers(x, y));
        }

        function plot(x, y) {
            var c = document.getElementById("myCanvas");
            var ctx = c.getContext("2d");
            ctx.clearRect(0, 0, c.width, c.height);
            ctx.beginPath();
            ctx.moveTo(x[0] + c.width / 2, y[0] + c.height / 2);
            for (var i = 1; i < x.length; i++) {
                ctx.lineTo(x[i] + c.width / 2, y[i] + c.height / 2);
            }
            ctx.strokeStyle = "red";
            ctx.stroke();
        }

        function fire() {
            // inputs
            nout = parseFloat(document.getElementById('nout').value); // number of teeth on the frame
            nin = parseFloat(document.getElementById('nin').value); // number of teeth on the gear
            p = parseFloat(document.getElementById('p').value); // position of hole. 0: center. 1: edge
            // nout = 96; // number of teeth on the frame
            // nin = 31; // number of teeth on the gear
            // p = 1; // position of hole. 0: center. 1: edge
            // parameters
            rout = 380; // radius of frame
            rin = rout / nout * nin; // radius of gear
            dt = 0.01; // step size in rad
            teeth = rout * Math.PI * 2 / nout; // teeth size in arc length
            // holders
            var x = [];
            var y = [];
            theta = 0; // position of gear
            alpha = 0; // rotation of the gear
            while (theta * rout / teeth < lcm(nout, nin)) {
                theta += dt;
                alpha += dt - dt * rout / rin;
                // center of gear
                xc = Math.cos(theta) * (rout - rin)
                yc = Math.sin(theta) * (rout - rin)
                // position of hole
                xh = xc + Math.cos(alpha) * rin * p
                yh = yc + Math.sin(alpha) * rin * p
                // append
                x.push(xh)
                y.push(yh)
            }

            plot(x, y);
        }

        fire();
    </script>
</body>

</html>